services:
  - type: web
    name: prepguardian
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: AI_PROVIDER
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: AI_BASE_URL
        sync: false
      - key: AI_MODEL
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GOOGLE_SEARCH_API_KEY
        sync: false
      - key: GOOGLE_SEARCH_ENGINE_ID
        sync: false
